version: "3.9"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        depends_on: 
            - postgres
        environment:
            STAGE: prod
            POSTGRES_PORT: 5432
            POSTGRES_HOST: 194.249.251.33
            POSTGRES_USER: skillup0113
            POSTGRES_PASSWORD: Pr3s3nt-35
            POSTGRES_DB: Rogelsek_SkillUp_02
            NODE_ENV: development
            PORT: 8080
            JWT_SECRET: R232padxEkf6kaeFGZBV9UFWEWft7wzfJhtBLce52qzPyrafj6fSNCTbTZRaTkuw
            AWS_STORAGE_BUCKET_NAME: geotagger-image-upload
            AWS_BUCKET_REGION: eu-central-1
            AWS_ACCESS_KEY_ID: AKIAUBFBQZEI7SBDQB6G
            AWS_SECRET_ACCESS_KEY: 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
            SENDGRID_API_KEY: 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
        ports:
            - "8080:8080"

    postgres:
        image: postgres:13
        ports:
            - "35000:5432"
        environment:
            POSTGRES_PORT: 5432
            POSTGRES_HOST: 194.249.251.33
            POSTGRES_USER: skillup0113
            POSTGRES_PASSWORD: Pr3s3nt-35
            POSTGRES_DB: Rogelsek_SkillUp_02
